version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=DBname
      - POSTGRES_USER=nameuser
      - POSTGRES_PASSWORD=123123qwerty
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data